name: Windows Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make

      - name: Build with batch script
        shell: msys2 {0}
        run: ./build.bat -compile

      - name: Download OpenAL32.dll
        run: curl -L -o OpenAL32.dll https://github.com/raysan5/raylib/releases/download/4.5.0/OpenAL32.dll

      - name: Upload executable, DLL, and resources
        uses: actions/upload-artifact@v4
        with:
          name: compiled-exe
          path: |
            ./*.exe
            ./OpenAL32.dll
            ./resources/**
